### ISSUE TITLE
关于字符串数组的解析错误

### ISSUE THREAD

**Issue by CasonTsai** [sunchb/cson#1]
谢谢作者提供这么好的代码，想问下是不是现在不能解析字符串数组，
在测试test1.c时出现错误
!!!!parse error on field:strList, cod=-3!!!!
decode ret=0

**Comment by sunchb** [comment]
感谢反馈。
目前master上支持任何类型（包括字符串，数字，布尔，对象）的一维数组。(多维数组的支持目前没有合并到master，暂时放在dev3分支上)

为了提高测试代码的覆盖率，制作了缺少某些字段的测试数据，所以运行test1时会提示cod = -3（没有找到相应字段ERR_MISSING_FIELD）。

**Comment by CasonTsai** [comment]
嗯嗯，谢谢大佬
