### ISSUE TITLE
关于struct转raw json

### ISSUE THREAD

**Issue by CasonTsai** [sunchb/cson#2]
不好意思额，又来麻烦大佬，，按照教程可以成功跑通，
![image](https://user-images.githubusercontent.com/18262642/93226124-8fa76c00-f7a5-11ea-969a-1bde17357e9a.png)
这是成功转换的json字符串，如果想转成如下图的raw json的话
![image](https://user-images.githubusercontent.com/18262642/93226271-b6fe3900-f7a5-11ea-8b87-b23ef85e495b.png)
，里面有提供接口么，还是要自己修改print_value函数

**Comment by CasonTsai** [comment]
描述错误，应该是加入转义字符的意思

**Comment by sunchb** [comment]
现在没有这样的接口。

因为这个库底层调用的是jansson或者cjson，你可以调查一下jansson和cjson有没有类似的功能，然后修改jansson_impl_to_string/cjson_impl_to_string函数来实现。

另外请问一下你贴出的图2是怎么序列化的？（使用了哪个库以及序列化的参数）

**Comment by CasonTsai** [comment]
嗯嗯，谢谢大佬，图2是用的postman，后台那里要求有转义字符的，，把这个后台的字符串贴入到postman,里面有转code的工具，转出来就是这样了

**Comment by sunchb** [comment]
好吧，那可能只能调查一下jansson和cjson有没有支持转义的接口或者参数了。

**Comment by CasonTsai** [comment]
嗯嗯，谢谢大佬
